SdwanUSerList/sdwan/sdwan/urls.py
from django.contrib import admin
from django.urls import path
from user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user1', views.user1),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]

SdwanUSerList/sdwan/user/models.py
# -*- coding: utf-8 -*-


from django.db import models

# Create your models here.

class User(models.Model):
    ID = models.CharField(max_length=255)
    User_name = models.CharField(max_length=255)
    Company = models.CharField(max_length=255)
    City = models.CharField(max_length=255)
    DATE = models.DateField()
    Device_Serial_Number = models.CharField(max_length = 255)
    
    class Meta:
        db_table = "infinity_user"
    
    # def __str__(self):
    #     return self.User_name

SdwanUSerList/sdwan/user/forms.py
from django import forms  
from user.models import User 

class UserForm(forms.ModelForm):
    
     
    class Meta:  
        model = User
        fields = "__all__"

SdwanUSerList/sdwan/user/views.py
# -*- coding: utf-8 -*-


from django.shortcuts import render, redirect
from user.forms import UserForm
from user.models import User

# Create your views here.

def user1(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = UserForm()
    return render(request,'index.html',{'form':form})
    
    
def show(request):
    user_list = User.objects.all()
    return render (request,'show.html',{'user_list':user_list})


def edit(request,id):
    user_list = User.objects.get(id=id)
    form = UserForm(request.POST,instance = user_list)
    return render(request,'edit.html',{'user_list':user_list})


def update(request,id):
    user_list = User.object.get(id=id)
    form = UserForm(request.POST,instance = user_list)
    if form.is_valid():
        form.save()
        return redirect('/show')
    return render(request,'edit.html',{'user_list':user_list})



def destroy(request,id):
    user_list = User.objects.get(id=id)
    user_list.delete()
    return redirect('/show')




# def index(request):
#     return render(request, 'vyos/index1.html')

# def User1(request):
#     user_list = User.objects.order_by('-date')
#     return user_list

SdwanUSerList/sdwan/user/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/update/{{infinity_user.ID}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">ID:</label>
    <div class="col-sm-4">
        <input type="text" name="ID" id="id_ID" required maxlength="20" value="{{ infinity_user.ID }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">USER NAME:</label>
    <div class="col-sm-4">
        <input type="text" name="User_name" id="id_User_name" required maxlength="100" value="{{ infinity_user.User_name }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">COMPANY:</label>
    <div class="col-sm-4">
        <input type="text" name="Company" id="id_Company" required maxlength="254" value="{{ infinity_user.Company }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">CITY:</label>
    <div class="col-sm-4">
        <input type="text" name="City" id="id_City" required maxlength="15" value="{{ infinity_user.City }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">DATE:</label>
    <div class="col-sm-4">
        <input type="text" name="DATE" id="id_DATE" required maxlength="15" value="{{ infinity_user.DATE }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">DEVICE SERIAL NUMBER:</label>
    <div class="col-sm-4">
        <input type="text" name="Device_Serial_Number" id="id_Device_Serial_Number" required maxlength="15" value="{{ infinity_user.Device_Serial_Number }}" />
    </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update Entry</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

SdwanUSerList/sdwan/user/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/user1">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Enter Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">ID:</label>
    <div class="col-sm-4">
      {{ form.ID }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">User_name:</label>
    <div class="col-sm-4">
      {{ form.User_name }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Company:</label>
    <div class="col-sm-4">
      {{ form.Company }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">City:</label>
    <div class="col-sm-4">
      {{ form.City }}
    </div>
  </div>
    </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">DATE:</label>
    <div class="col-sm-4">
      {{ form.DATE }}
    </div>
  </div>
     </div>
    </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Device_Serial_Number:</label>
    <div class="col-sm-4">
      {{ form.Device_Serial_Number }}
    </div>
    
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

SdwanUSerList/sdwan/user/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>User Records</title>  
     {% load staticfiles %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>
<h1>Infinity SD_WAN Users List</h1>

<link rel="stylesheet" href="{% static "css/demodjproject.css" %}">
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">
    <table border="1"> 
    <tr>  
        <th>ID</th>
        <th>User_name</th>  
        <th>Company</th>  
        <th>City</th>  
        <th>DATE</th>
        <th>Device_Serial_Number</th>  
    </tr>  
    </thead>  
    <tbody>

        {% for infinity_user in user_list %} 
        <tr>
            <td>{{ infinity_user.ID }}</td>
            <td>{{ infinity_user.User_name }}</td>  
            <td>{{ infinity_user.Company }}</td>  
            <td>{{ infinity_user.City }}</td>  
            <td>{{ infinity_user.DATE }}</td>
            <td>{{ infinity_user.Device_Serial_Number }}</td> 
            <td>  
                <a href="/edit/{{ infinity_user.ID }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
                <a href="/delete/{{ infinity_user.ID }}">Delete</a>  
            </td>  
        </tr>
    {% endfor %} 
       
          
    </tbody>  
</table>  
<br>  
<br>
<table border="1">
 
<center><a href="/user1" class="btn btn-primary"><b><h1>Add New User</h1></b></a></center>  
</body>  
</html>  